name: "main"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Shellcheck
        run: shellcheck ${GITHUB_WORKSPACE}/dflink
